{"name": "# User goes to contact and fills out the fields. System allows and text: is here after submitting.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[@class='hero__excerpt']//h4[contains(text(),'We will be in touch very soon! We appreciate your inquiry, and a member of our team will be in touch as soon as possible.')]\"}\n  (Session info: chrome=81.0.4044.129)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contact_form.py\", line 45, in txt_hr\n    context.app.cntct_frm_page.txt_hr(txt_cnfrmtn)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\gpsenterprise\\pages\\cntct_frm_page.py\", line 90, in txt_hr\n    self.verify_text(text, *self.TXT_HR)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\gpsenterprise\\pages\\base_page.py\", line 34, in verify_text\n    actual_text = self.driver.find_element(*locator).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1591700042059, "stop": 1591700043447}, {"name": "Then Click on Contact button", "status": "passed", "start": 1591700043447, "stop": 1591700043842}, {"name": "Then User enters First name Vic", "status": "passed", "start": 1591700043842, "stop": 1591700047950}, {"name": "Then User enters Last name Gurov", "status": "passed", "start": 1591700047950, "stop": 1591700048023}, {"name": "Then User enters Company name NA", "status": "passed", "start": 1591700048023, "stop": 1591700048095}, {"name": "Then User enters Job Title QA", "status": "passed", "start": 1591700048095, "stop": 1591700048155}, {"name": "Then User enters Email gurovvic@gmail.com", "status": "passed", "start": 1591700048155, "stop": 1591700048257}, {"name": "Then User enters Phone number 4074354433", "status": "passed", "start": 1591700048257, "stop": 1591700048349}, {"name": "Then User enters into the Message field Test for QA purposes", "status": "passed", "start": 1591700048349, "stop": 1591700052468}, {"name": "Then User agrees with I agree to receive other communications from Analytic Partners", "status": "passed", "start": 1591700052468, "stop": 1591700052571}, {"name": "Then User clicks on Submit button", "status": "passed", "start": 1591700052571, "stop": 1591700056664}, {"name": "Then Verify there is a text We will be in touch very soon! We appreciate your inquiry, and a member of our team will be in touch as soon as possible.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[@class='hero__excerpt']//h4[contains(text(),'We will be in touch very soon! We appreciate your inquiry, and a member of our team will be in touch as soon as possible.')]\"}\n  (Session info: chrome=81.0.4044.129)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contact_form.py\", line 45, in txt_hr\n    context.app.cntct_frm_page.txt_hr(txt_cnfrmtn)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\gpsenterprise\\pages\\cntct_frm_page.py\", line 90, in txt_hr\n    self.verify_text(text, *self.TXT_HR)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\gpsenterprise\\pages\\base_page.py\", line 34, in verify_text\n    actual_text = self.driver.find_element(*locator).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1591700056664, "stop": 1591700060711}], "start": 1591700032619, "stop": 1591700062917, "uuid": "287040cc-24af-4364-8e1d-4038a483a851", "historyId": "03aa2444ad3d9b808829e3fe07af5344", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# contact_form"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}