{"name": "# User goes to contact and fills out the fields. System allows and text: is here after submitting.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[@class='hero__excerpt']//h4[contains(text(),'We will be in touch very soon! We appreciate your inquiry, and a member of our team will be in touch as soon as possible.')]\"}\n  (Session info: chrome=81.0.4044.129)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contact_form.py\", line 45, in txt_hr\n    context.app.cntct_frm_page.txt_hr(txt_cnfrmtn)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\gpsenterprise\\pages\\cntct_frm_page.py\", line 90, in txt_hr\n    self.verify_text(text, *self.TXT_HR)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\gpsenterprise\\pages\\base_page.py\", line 34, in verify_text\n    actual_text = self.driver.find_element(*locator).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1591700312817, "stop": 1591700314239}, {"name": "Then Click on Contact button", "status": "passed", "start": 1591700314240, "stop": 1591700315232}, {"name": "Then User enters First name Vic", "status": "passed", "start": 1591700315233, "stop": 1591700334586}, {"name": "Then User enters Last name Gurov", "status": "passed", "start": 1591700334586, "stop": 1591700334658}, {"name": "Then User enters Company name NA", "status": "passed", "start": 1591700334658, "stop": 1591700334731}, {"name": "Then User enters Job Title QA", "status": "passed", "start": 1591700334731, "stop": 1591700334787}, {"name": "Then User enters Email gurovvic@gmail.com", "status": "passed", "start": 1591700334787, "stop": 1591700334882}, {"name": "Then User enters Phone number 4074354433", "status": "passed", "start": 1591700334882, "stop": 1591700334979}, {"name": "Then User enters into the Message field Test for QA purposes", "status": "passed", "start": 1591700334979, "stop": 1591700339123}, {"name": "Then User agrees with I agree to receive other communications from Analytic Partners", "status": "passed", "start": 1591700339123, "stop": 1591700339217}, {"name": "Then User clicks on Submit button", "status": "passed", "start": 1591700339217, "stop": 1591700343282}, {"name": "Then Verify there is a text We will be in touch very soon! We appreciate your inquiry, and a member of our team will be in touch as soon as possible.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[@class='hero__excerpt']//h4[contains(text(),'We will be in touch very soon! We appreciate your inquiry, and a member of our team will be in touch as soon as possible.')]\"}\n  (Session info: chrome=81.0.4044.129)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\contact_form.py\", line 45, in txt_hr\n    context.app.cntct_frm_page.txt_hr(txt_cnfrmtn)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\gpsenterprise\\pages\\cntct_frm_page.py\", line 90, in txt_hr\n    self.verify_text(text, *self.TXT_HR)\n  File \"C:\\Everything\\My_docs\\Self_development\\IT\\Testing\\Automation_08_09_2019\\gpsenterprise\\pages\\base_page.py\", line 34, in verify_text\n    actual_text = self.driver.find_element(*locator).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1591700343282, "stop": 1591700347317}], "start": 1591700303562, "stop": 1591700349555, "uuid": "202402e7-1ce7-4d21-aa37-5751eeb19d8f", "historyId": "03aa2444ad3d9b808829e3fe07af5344", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# contact_form"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}